# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /bbs

spring:
  # 运行环境配置
  profiles:
    active: dev
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${para.datasource.url}
    username: ${para.datasource.username}
    password: ${para.datasource.password}
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 25MB
  data:
    # Redis 配置
    redis:
      host: ${para.redis.host}
      port: ${para.redis.port}
      password: ${para.redis.password}
      database: ${para.redis.database}
      # 连接超时
      connect-timeout: ${para.redis.connect-timeout}
      # 命令执行超时
      timeout: ${para.redis.timeout}

      # Lettuce 配置
      lettuce:
        pool:
          max-active: ${para.redis.lettuce.pool.max-active} # 最大连接数
          max-idle: ${para.redis.lettuce.pool.max-idle} # 最大空闲连接
          min-idle: ${para.redis.lettuce.pool.min-idle} # 最小空闲连接
          max-wait: ${para.redis.lettuce.pool.max-wait} # 最大等待时间，超时报错
  # Elastic Search
  elasticsearch:
    uris: ${para.elasticsearch.uris}
    connection-timeout: 3s
    socket-timeout: 5s
  # RabbitMQ
  rabbitmq:
    host: ${para.rabbitmq.host}
    port: ${para.rabbitmq.port}
    username: ${para.rabbitmq.username}
    password: ${para.rabbitmq.password}
    virtual-host: ${para.rabbitmq.virtual-host}

    publisher-confirm-type: correlated
    publisher-returns: true

    template:
      mandatory: true

    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 20
        default-requeue-rejected: false
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 1s
          multiplier: 2
          max-interval: 10s


# MyBatis配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cn.nobeta.bbs.module
  configuration:
    map-underscore-to-camel-case: true  # 开启驼峰命名

# jwt配置
jwt: 
  secret: ${para.jwt.secret}
  access-token-expire: ${para.jwt.access-token-expire}
  refresh-token-expire: ${para.jwt.refresh-token-expire}

# PageHelper配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  default-count: true
  support-methods-arguments: true

para:
  # 文件存储位置
  file:
    managed:
      public-base-url: ${PARA_FILE_PUBLIC_BASE_URL:http://localhost:8080/bbs/i/}
      root-path: ${PARA_FILE_ROOT_PATH:./data/}
      avatar-max-size: 10485760
      max-size: 15728640  # 背景图与封面大小上限
      expire: 2
    image:
      max-size: 15728640
  # Github配置
  github:
    branch: main
    name: Nobeta
    email: 377877931@qq.com
    owner: Nobeta-Work
    repo: faramita-bbs-file
    path: img/
    token: ${para.github.token}


